CREATE TABLE LIBRARY (NAME varchar(255) NOT NULL, LOCATION VARCHAR(255) NOT NULL, PRIMARY KEY (NAME));
CREATE TABLE PUBLISHER (PUBLISHERID INT NOT NULL, NAME VARCHAR(255) NOT NULL, PRIMARY KEY (PUBLISHERID));
CREATE TABLE AUTHOR (ID INT NOT NULL, NAME VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE ITEM (ITEMID INT NOT NULL, NAME varchar(255) NOT NULL, AVAILABLE INT, LOCATIONCODE INT, LIBRARY_NAME varchar(255) NOT NULL, 
                   PUBLISHERID INT,
                   FOREIGN KEY (LIBRARY_NAME) REFERENCES LIBRARY(NAME),
                  FOREIGN KEY (PUBLISHERID) REFERENCES PUBLISHER(PUBLISHERID),
                  PRIMARY KEY (ITEMID));
CREATE TABLE BOOK (BOOKID INT NOT NULL, PAGE INT, FOREIGN KEY (BOOKID) REFERENCES ITEM(ITEMID), PRIMARY KEY (BOOKID))
CREATE TABLE CD (CDID INT NOT NULL, LENGTH INT, FOREIGN KEY (CDID) REFERENCES ITEM(ITEMID), PRIMARY KEY (CDID))
CREATE TABLE MAGAZINE (MAGAZINEID INT NOT NULL, PAGE INT, FOREIGN KEY (MAGAZINEID) REFERENCES ITEM(ITEMID), PRIMARY KEY (MAGAZINEID))
CREATE TABLE WRITE (AUTHOR_ID INT NOT NULL, ITEM_ID INT NOT NULL,
                    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
                    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEMID),
                   PRIMARY KEY (AUTHOR_ID, ITEM_ID ) )
CREATE TABLE GENRE (GENRE VARCHAR(255), ITEM_ID INT NOT NULL,
                    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEMID),
                   PRIMARY KEY (GENRE, ITEM_ID))
CREATE TABLE LOGIN (USERNAME VARCHAR(255) NOT NULL, LIBRARY_NAME VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255), USERTYPE VARCHAR(255),
                   FOREIGN KEY (LIBRARY_NAME) REFERENCES LIBRARY(NAME), PRIMARY KEY (USERNAME, LIBRARY_NAME))
                   
                                      
CREATE TABLE LIBRARIAN (LIBRARIAN_ID INT NOT NULL,LIBRARY_NAME VARCHAR(255) NOT NULL, NAME VARCHAR(255), USERNAME VARCHAR(255),
                        FOREIGN KEY (LIBRARY_NAME) REFERENCES LIBRARY(NAME),
                        FOREIGN KEY (USERNAME) REFERENCES LOGIN(USERNAME),
                        PRIMARY KEY (LIBRARIAN_ID,LIBRARY_NAME))
CREATE TABLE STUDENT (STUDENT_ID INT NOT NULL,FALCULTY VARCHAR(255) NOT NULL, NAME VARCHAR(255), USERNAME VARCHAR(255), PHONE INT,
                        FOREIGN KEY (USERNAME) REFERENCES LOGIN(USERNAME),
                        PRIMARY KEY (STUDENT_ID))   
CREATE TABLE BORROW (STUDENT_ID INT NOT NULL,ITEM_ID INT NOT NULL, DATE1 DATE , OVERDUE INT,
                        FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
                    	FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEMID),
                    	PRIMARY KEY (STUDENT_ID));

CREATE TABLE RETURN1 (STUDENT_ID INT NOT NULL, ITEM_ID INT NOT NULL, BORROWDATE DATE , RETURNDATE DATE,
                        FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
                    	FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEMID),
                    	PRIMARY KEY (STUDENT_ID, ITEM_ID,BORROWDATE ));
                     
CREATE TABLE FINE (FINEID INT NOT NULL, STUDENT_ID INT NOT NULL, ITEM_ID INT NOT NULL, AMOUNT INT, CHARGE_DATE DATE NOT NULL, PAID_DATE DATE NOT NULL
                   FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
                   FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEMID),
                  PRIMARY KEY (FINEID,STUDENT_ID ))
