INSERT INTO LIBRARY (name, location ) VALUES ('LIBRARY0', 'Calgary');
INSERT INTO LIBRARY (name, location ) VALUES ('LIBRARY1', 'Vancouver');
INSERT INTO LIBRARY (name, location ) VALUES ('LIBRARY2', 'Toronto');

INSERT INTO PUBLISHER (NAME) VALUES ('PUBLISHER0');
INSERT INTO PUBLISHER (NAME) VALUES ('PUBLISHER1');
INSERT INTO PUBLISHER (NAME) VALUES ('PUBLISHER2');

INSERT INTO AUTHOR (NAME) VALUES ('AUTHOR0');
INSERT INTO AUTHOR (NAME) VALUES ('AUTHOR1');
INSERT INTO AUTHOR (NAME) VALUES ('AUTHOR2');

INSERT INTO ITEM (NAME, AVAILABLE, LOCATIONCODE, LIBRARY_NAME, PUB_ID) 
    VALUES ('Test Book0', 1 , 40 ,'LIBRARY0', 1);
INSERT INTO ITEM (NAME, AVAILABLE, LOCATIONCODE, LIBRARY_NAME, PUB_ID)
    VALUES ('Test Book1', 2 , 40 ,'LIBRARY0', 1);
INSERT INTO ITEM (NAME, AVAILABLE, LOCATIONCODE, LIBRARY_NAME, PUB_ID) 
    VALUES ('Test Book2', 3 , 40 ,'LIBRARY0', 2);
INSERT INTO ITEM (NAME, AVAILABLE, LOCATIONCODE, LIBRARY_NAME, PUB_ID) 
    VALUES ('Test CD', 2 , 41 ,'LIBRARY0', 2);
INSERT INTO ITEM (NAME, AVAILABLE, LOCATIONCODE, LIBRARY_NAME, PUB_ID) 
    VALUES ('Test Magazine', 1, 42, 'LIBRARY0', 3);

INSERT INTO BOOK VALUES (1, 100);
INSERT INTO BOOK VALUES (2, 200);
INSERT INTO BOOK VALUES (3, 456);
INSERT INTO CD VALUES (4, 20);
INSERT INTO MAGAZINE VALUES (5, 69);
  
INSERT INTO WRITES VALUES (1, 1);
INSERT INTO WRITES VALUES (2, 2);
INSERT INTO WRITES VALUES (3, 3);

INSERT INTO GENRE VALUES (1, 'Fantasy');
INSERT INTO GENRE VALUES (2, 'Science Fiction');
INSERT INTO GENRE VALUES (3, 'Mystery');
INSERT INTO GENRE VALUES (4, 'Mystery');
INSERT INTO GENRE VALUES (5, 'Culture');

INSERT INTO LOGIN VALUES ('student', 'LIBRARY0','password','STUDENT');
INSERT INTO LOGIN VALUES ('librarian', 'LIBRARY0','password','LIBRARIAN');
INSERT INTO LOGIN VALUES ('admin', 'LIBRARY0','password', 'SYSADMIN');

INSERT INTO LIBRARIAN (LIBRARY_NAME, NAME, USERNAME) 
    VALUES ('LIBRARY0','Test Librarian','librarian');
INSERT INTO LIBRARIAN (LIBRARY_NAME, NAME, USERNAME) 
    VALUES ('LIBRARY0','Test Sysadmin','admin');

INSERT INTO STUDENT (NAME, FACULTY, PHONE, USERNAME, LIBRARY_NAME) 
    VALUES ('Test Student','Science','123-456-7890', 'student', 'LIBRARY0');

INSERT INTO BORROW VALUES (1, 1, '2021-12-01', 0);

INSERT INTO RETURN1 VALUES (1, 2, '2021-5-02', '2021-7-07');

INSERT INTO FINE (STUDENT_ID, ITEM_ID, AMOUNT, CHARGE_DATE, PAY_DATE) 
    VALUES (1, 2, 5.00, '2021-7-07','2021-7-10');