INSERT INTO LIBRARY (name, location ) VALUES ('LIBRARYNAME1', 'Calgary');
INSERT INTO LIBRARY (name, location ) VALUES ('LIBRARYNAME2', 'Vancouver');
INSERT INTO LIBRARY (name, location ) VALUES ('LIBRARYNAME3', 'Toronto');

-- LIBRARY ID START WITH 1
INSERT INTO PUBLISHER VALUES (10, 'PUBLISHER0');
INSERT INTO PUBLISHER VALUES (11, 'PUBLISHER1');
INSERT INTO PUBLISHER VALUES (12, 'PUBLISHER2');

-- AUTHOR ID START WITH 2
INSERT INTO AUTHOR VALUES (20, 'AUTHOR0');
INSERT INTO AUTHOR VALUES (21, 'AUTHOR1');
INSERT INTO AUTHOR VALUES (22, 'AUTHOR2');

-- ITEM ID START WITH 3, LOCATION CODE START WITH 4
INSERT INTO ITEM VALUES (30, 'ITEM0', 1 , 40 ,'LIBRARYNAME1', 10);
INSERT INTO ITEM VALUES (31, 'ITEM1', 2 , 41 ,'LIBRARYNAME2', 11);
INSERT INTO ITEM VALUES (32, 'ITEM2', 3, 42, 'LIBRARYNAME3', 12);

INSERT INTO BOOK VALUES (30, 100);
INSERT INTO CD VALUES (31, 20);
INSERT INTO MAGAZINE VALUES (32, 69);
  
INSERT INTO WRITES VALUES (20, 30);
INSERT INTO GENRE VALUES ('FICTION', 30);

INSERT INTO LOGIN VALUES ('USERNAME1', 'LIBRARYNAME1','PASSWORD1','STUDENT');
INSERT INTO LOGIN VALUES ('USERNAME2', 'LIBRARYNAME2','PASSWORD2','LIBRARIAN');

-- LIRARIAN ID STARTS WITH 5
INSERT INTO LIBRARIAN VALUES (50, 'LIBRARYNAME2','NAME1','USERNAME2');

-- STUDENT ID STARTS WITH 6
INSERT INTO STUDENT VALUES (60,'SCIENCE','STUDENTNAME1','USERNAME1', 123245312);

INSERT INTO BORROW VALUES (60, 30,'2008-7-04', 5);

INSERT INTO RETURN1 VALUES (60,31, '2008-7-05', '2008-7-07');

-- FINE ID START WITH 7
INSERT INTO FINE VALUES (70,60, 30, 5,'2008-7-09','2008-7-10');